### ISSUE TITLE
Use NPMap Builder Custom Map Option

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-species#107]
@nateirwin , we're wanting to use the NPMap Builder Custom Map Option so we can embed the map that is here https://github.com/nationalparkservice/npmap-species/blob/gh-pages/denvercode/index.html within CMS. This will be the landing/launch page for https://github.com/nationalparkservice/npmap-species/tree/gh-pages/denvercode/full. Launch date May 15....

**Comment by tpcolson** [comment]
A note on the landing page, All of my content in the html (it's a massive file) should be between the lines: '' and ''. So, when you go to put in your CMS you should only want to take that content from my html and place it in whatever template the CMS provides.

If you have any questions about this, please let me know.

Thanks!
John

**Comment by tpcolson** [comment]
Landing page will go here: 
https://www.nps.gov/grsm/learn/nature/biodiversity.htm

**Comment by tpcolson** [comment]
Julie any status on this?

**Comment by KendraStraub** [comment]
Status?
