### ISSUE TITLE
When "live", site does not load in IE 11

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-species#120]
Appears to be related to the Report an Issue Link. From https://science.nature.nps.gov/parks/grsm/species/

![image](https://cloud.githubusercontent.com/assets/5861784/15508034/e9cb866a-219b-11e6-88e8-ff08ce21eda8.png)

**Comment by jduggan1** [comment]
I believe this should be fixed with https://github.com/nationalparkservice/npmap-species/commit/d2b472f50351c8360ece99199020815119d47bc0. If it's still not working, let me know.

**Comment by tpcolson** [comment]
Nope....still not working....
![image](https://cloud.githubusercontent.com/assets/5861784/21817524/4b64c7aa-d732-11e6-9e2b-594079960f25.png)

**Comment by auxiliary** [comment]
@tpcolson I just checked this and it renders fine on my IE11. Could you please give it another test?

**Comment by KendraStraub** [comment]
Still does not work on IE11... looks like the picture @tpcolson  uploaded last year on my machine still.
