### ISSUE TITLE
Upgrade to Park Tile 3.0

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-species#122]
@nateirwin would like to do a merge/pull on the Denver/Full code to upgrade the base map to Park Tiles 3.0 to maintain compatibility with the rest of the NPS Centennial redesign. @huang-utk do you approve?

**Comment by huang-utk** [comment]
@jduggan1, do you anticipate any issues if we go up to Park Tiles 3.0?

**Comment by tpcolson** [comment]
@nateirwin can you make a branch, make the change, and we'll test before merging?

**Comment by tpcolson** [comment]
Just thought of this: 

PT 3.0 uses vector tile which uses campsites, etc...as you zoom in. @nateirwin one part of the user experience we wanted was for folks to be able to turn those vector features on or off regardless of zoom level. We might have to either go with a custom PT 3.0 css, or re-visit how we turn those features on and off at user GUI. Either way, let's still test.

**Comment by jduggan1** [comment]
Depends on what it looks like. The beta version I found was only viewable on the NPS intranet; is there somewhere else I can see it?

**Comment by nateirwin** [comment]
https://github.com/nationalparkservice/npmap.js/blob/master/src/preset/baselayers.json#L263

The vector overlay is optional, so using the Mapbox ids captured in the linked JSON will not bring the POIs in. Your custom POIs will continue to work.

**Comment by jduggan1** [comment]
Thanks! If you all want to look at it before updating the live site here's the URL: http://seelab.eecs.utk.edu/species_mapper/full/

I don't think there will be any issues, but I will defer to you all.

**Comment by nateirwin** [comment]
That looks great! One other minor suggestion: If you update NPMap.js to 3.0.17 (just change the URL path), you'll get a fix that addresses a few minor Safari issues.

Other than that, no recommendations... great job!

**Comment by tpcolson** [comment]
Was this done? Can we close this?

**Comment by jduggan1** [comment]
It is updated in the repo, but it looks like the version running on nps.gov hasn't been updated with this change yet.

**Comment by KendraStraub** [comment]
@tpcolson  - can this be closed?

**Comment by auxiliary** [comment]
This should be checked and if needed changed to version 4.0
