### ISSUE TITLE
Need list of GRSM Tile Packages in NPS MB Account

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-species#135]
Need list of GRSM Tile Packages in NPS MB Account that are sourced by the Species Mapper API Key to compare with species lists. Will likely need to delete some.

**Comment by jduggan1** [comment]
[mb_strings.txt](https://github.com/nationalparkservice/npmap-species/files/717544/mb_strings.txt)

Here's the list of tile packages that should have been uploaded to mapbox the last time we processed an extract.

**Comment by tpcolson** [comment]
Copy. This workflow should be updated so the tile name and address is added to some sort of master output csv

**Comment by KendraStraub** [comment]
Can this be closed? @tpcolson

**Comment by tpcolson** [comment]
@s-vaddey @jakecoolidge @yetiracing4als see https://github.com/nationalparkservice/npmap-species/files/717544/mb_strings.txt can we get a list of GRSM-owned tiles in Mapbox so we can reconcile?
