### ISSUE TITLE
Load JSON files from a different server other than Github.io

### ISSUE THREAD

**Issue by auxiliary** [tpcolson/npmap-species#150]
Github.io should not be used for hosting data.

**Comment by tpcolson** [comment]
hmmmm....I thought we fixed this? What is being served from GH?

**Comment by auxiliary** [comment]
At the moment the following files are being served from GH:

- lexical_index.json
- irma_mapping.json
- most_similar_distribution.json
- species_auc.json

**Comment by tpcolson** [comment]
ok. Is there a way we could serve those straight from the web server, same (root) directory the rest of the stuff is in? Or create an assets folder?

**Comment by auxiliary** [comment]
Yes, I believe that would be okay. I'll make a note and make this change in the next revision.

**Comment by auxiliary** [comment]
This issue is also making AdBlock block our layer updates.
