### ISSUE TITLE
"name convention" toggle 

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-species#173]
2.	Seems odd to have the "name convention" toggle (common to latin) under the "group selector" section of the species mapper when viewed as "common grouping" - perhaps it should shift to the "individual species from group" section in this use case

**Comment by 3PIV** [comment]
Move to species toggle selection area

**Comment by 3PIV** [comment]
Solved by commit a19063b - toggle moved to species select dropdown in group view.
