### ISSUE TITLE
Update landing page map js

### ISSUE THREAD

**Issue by tpcolson** [tpcolson/npmap-species#95]
http://seelab.eecs.utk.edu/species_mapper/ should look and function as http://www.nps.gov/grsm/planyourvisit/waterfalls.htm, e.g the font/placement of disclaimer text, etc..

Not sure what to do about what functionality the landing page should have, as it's too small for anything, really? Map a single-button clicky thingy to the full site? 

Or perhaps, a simple drop down of just species that shows species tiles, no other tools, click the full screen button to get the other tools.

**Comment by KendraStraub** [comment]
@tpcolson -- The landing page won't have the species mapper, it will have some sort of biodiversity map. That is what we decided a few meetings back.

**Comment by jduggan1** [comment]
Sarah has already given me a design for updated landing page, which I will try to implement by Monday. Once done, I'll send you the link for review.

**Comment by jduggan1** [comment]
Finished with https://github.com/nationalparkservice/npmap-species/commit/4b074fb25cfb8303b6235dc87e585de9bd775d75. Let me know what you're thoughts are.

**Comment by KendraStraub** [comment]
Sarah is working on landing page content. It will include the video.

**Comment by KendraStraub** [comment]
Not relevant - landing page complete - no live map in it.
